title: Mohit Yadav
logo: /Circle_Headshot.png
theme: jekyll-theme-minimal

description: |
  ## Skills  
  - **ğŸ“Š Data Analysis:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘  
  - **ğŸ”„ ETL:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘  
  - **ğŸ Python:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–‘  
  - **ğŸ—ƒï¸ SQL:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘  
  - **ğŸ“ˆ Power BI/Tableau:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘  
  - **ğŸ—ï¸ Data Design & Modeling:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–‘  
  - **ğŸ” Data Governance:** â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–‘  
